### ***Recurrent Neural Network(RNN)***
- ***A neural network designed for sequential data that maintains a hidden state to carry information from previous time steps.***

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/qa_dataset.csv")
df.head()

                                          question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [2]:
df.shape

(90, 2)

In [3]:
## Tokenize
def tokenize(text):
  text = text.lower()
  text = text.replace('?','')
  text = text.replace("'","")
  return text.split()

In [4]:
tokenize('What is the capital of France?')

['what', 'is', 'the', 'capital', 'of', 'france']

In [5]:
## vocab
vocab = {'<UNK>':0}

In [6]:
def build_vocab(row):
  tokenized_ques = tokenize(row['question'])
  tokenize_ans = tokenize(row['answer'])
  tokens = tokenized_ques + tokenize_ans

  for token in tokens:
    if token not in vocab:
      vocab[token] = len(vocab)

df.apply(build_vocab,axis=1)

0     None
1     None
2     None
3     None
4     None
      ...
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [7]:
len(vocab)

324

In [8]:
# word --> numerical indices
def text_indices(text,vocab):
  idx_text = []
  for token in tokenize(text):
    if token in vocab:
      idx_text.append(vocab[token])
    else:
      idx_text.append(vocab['<UNK>'])
  return idx_text

In [9]:
text_indices("Who is Ankit Gupta", vocab)

[10, 2, 0, 0]

In [10]:
import torch
from torch.utils.data import Dataset,DataLoader

class QA_Dataset(Dataset):
  def __init__(self,df,vocab):
    self.df = df
    self.vocab = vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self, index):
    numeric_ques = text_indices(self.df.iloc[index]['question'],self.vocab)
    numeric_ans = text_indices(self.df.iloc[index]['answer'],self.vocab)
    return torch.tensor(numeric_ques),torch.tensor(numeric_ans)

In [11]:
dataset = QA_Dataset(df,vocab)
dataloader = DataLoader(dataset,batch_size=1,shuffle=True)

In [12]:
for ques,ans in dataloader:
  print(ques,ans[0])

tensor([[42, 86, 87, 88, 89, 39, 90]]) tensor([91])
tensor([[ 1,  2,  3,  4,  5, 73]]) tensor([74])
tensor([[ 42, 290, 291, 118, 292, 158, 293, 294]]) tensor([295])
tensor([[10, 29,  3, 30, 31]]) tensor([32])
tensor([[  1,   2,   3, 146, 147,  19, 148]]) tensor([149])
tensor([[ 42, 167,   2,   3,  17, 168, 169]]) tensor([170])
tensor([[ 78,  79, 129,  81,  19,   3,  21,  22]]) tensor([36])
tensor([[ 42, 125,   2,  62,  63,   3, 126, 127]]) tensor([128])
tensor([[  1,   2,   3,  33,  34,   5, 245]]) tensor([246])
tensor([[78, 79, 80, 81, 82, 83, 84]]) tensor([85])
tensor([[  1,   2,   3, 234,   5, 235]]) tensor([131])
tensor([[ 10, 140,   3, 141, 142,  12, 143,  83,   3, 144]]) tensor([145])
tensor([[ 42,  86,  87, 241, 242,  19,  39, 243]]) tensor([244])
tensor([[ 1,  2,  3, 33, 34,  5, 35]]) tensor([36])
tensor([[ 10,  11, 189, 158, 190]]) tensor([191])
tensor([[ 10, 140,   3, 141, 171,   5,   3,  70, 172]]) tensor([173])
tensor([[ 1,  2,  3, 37, 38, 39, 40]]) tensor([41])
tensor([[10, 75, 76]]) tensor([77])
tensor([[10, 96,  3, 97]]) tensor([98])
tensor([[  1,   2,   3,   4,   5, 113]]) tensor([114])
tensor([[ 10, 308,   3, 309, 310]]) tensor([311])
tensor([[  1,   2,   3, 180, 181, 182, 183]]) tensor([184])
tensor([[  1,   2,   3,  37, 133,   5,  26]]) tensor([134])
tensor([[ 42, 174,   2,  62,  39, 175, 176,  12, 177, 178]]) tensor([179])
tensor([[  1,   2,   3,  17, 115,  83,  84]]) tensor([116])
tensor([[ 42, 312,   2, 313,  62,  63,   3, 314, 315]]) tensor([316])
tensor([[ 10,  75, 111]]) tensor([112])
tensor([[ 42, 200,   2,  14, 201, 202, 203, 204]]) tensor([205])
tensor([[10,  2,  3, 66,  5, 67]]) tensor([68])
tensor([[ 1,  2,  3, 92, 93, 94]]) tensor([95])
tensor([[ 42, 318,   2,  62,  63,   3, 319,   5, 320]]) tensor([321])
tensor([[ 42,   2,   3, 210, 137, 168, 211, 169]]) tensor([113])
tensor([[  1,   2,   3,   4,   5, 286]]) tensor([287])
tensor([[ 1,  2,  3, 24, 25,  5, 26, 19, 27]]) tensor([28])
tensor([[ 10, 140,   3, 141, 270,  93, 271,   5,   3, 272]]) tensor([273])
tensor([[ 42, 107,   2, 108,  19, 109]]) tensor([110])
tensor([[ 42, 137,   2,  62,  39,   3, 322, 323]]) tensor([6])
tensor([[10, 11, 12, 13, 14, 15]]) tensor([16])
tensor([[ 42,  18,   2,   3, 281,  12,   3, 282]]) tensor([205])
tensor([[  1,   2,   3, 146,  86,  19, 192, 193]]) tensor([194])
tensor([[ 1,  2,  3, 59, 25,  5, 26, 19, 60]]) tensor([61])
tensor([[  1,   2,   3,   4,   5, 135]]) tensor([136])
tensor([[ 42, 137,   2, 138,  39, 175, 269]]) tensor([99])
tensor([[ 1,  2,  3, 69,  5, 53]]) tensor([260])
tensor([[ 42, 117, 118,   3, 119,  94, 120]]) tensor([121])
tensor([[ 10,  11, 157, 158, 159]]) tensor([160])
tensor([[10, 55,  3, 56,  5, 57]]) tensor([58])
tensor([[ 78,  79, 150, 151,  14, 152, 153]]) tensor([154])
tensor([[  1,   2,   3,  37,  38,  39, 161]]) tensor([162])
tensor([[ 78,  79, 195,  81,  19,   3, 196, 197, 198]]) tensor([199])
tensor([[ 1,  2,  3, 50, 51, 19,  3, 45]]) tensor([52])
tensor([[ 10,  75, 208]]) tensor([209])
tensor([[  1,   2,   3,   4,   5, 109]]) tensor([317])
tensor([[ 1,  2,  3,  4,  5, 99]]) tensor([100])
tensor([[ 1,  2,  3, 69,  5,  3, 70, 71]]) tensor([72])
tensor([[  1,   2,   3, 163, 164, 165,  83,  84]]) tensor([166])
tensor([[ 1,  2,  3,  4,  5, 53]]) tensor([54])
tensor([[1, 2, 3, 4, 5, 8]]) tensor([9])
tensor([[ 10,   2,  62,  63,   3, 283,   5, 284]]) tensor([285])
tensor([[42, 18,  2, 62, 63,  3, 64, 18]]) tensor([65])
tensor([[ 42, 250, 251, 118, 252, 253]]) tensor([254])
tensor([[ 42,  18, 118,   3, 186, 187]]) tensor([188])
tensor([[ 42, 216, 118, 217, 218,  19,  14, 219,  43]]) tensor([220])
tensor([[ 10,  96,   3, 104, 239]]) tensor([240])
tensor([[ 42, 263, 264,  14, 265, 266, 158, 267]]) tensor([268])
tensor([[1, 2, 3, 4, 5, 6]]) tensor([7])
tensor([[ 42,   2,   3, 274, 211, 275]]) tensor([276])
tensor([[  1,   2,   3, 221,   5, 222, 223, 224]]) tensor([225])
tensor([[  1,   2,   3, 122, 123,  19,   3,  45]]) tensor([124])
tensor([[  1,   2,   3, 103,   5, 104,  19, 105]]) tensor([106])
tensor([[ 78,  79, 288,  81,  19,  14, 289]]) tensor([85])
tensor([[ 42, 137, 118,   3, 247,   5, 248]]) tensor([249])
tensor([[ 1,  2,  3, 17, 18, 19, 20, 21, 22]]) tensor([23])
tensor([[ 10,  75,   3, 296,  19, 297]]) tensor([298])
tensor([[ 42, 137,   2, 226,  12,   3, 227, 228]]) tensor([155])
tensor([[  1,   2,   3, 141, 117,  83,   3, 277, 278]]) tensor([121])
tensor([[ 42, 299, 300, 118,  14, 301, 302, 158, 303, 304, 305, 306]]) tensor([307])
tensor([[ 78,  79, 261, 151,  14, 262, 153]]) tensor([36])
tensor([[  1,   2,   3,  69,   5, 155]]) tensor([156])
tensor([[  1,   2,   3,   4,   5, 279]]) tensor([280])
tensor([[  1,   2,   3,   4,   5, 236, 237]]) tensor([238])
tensor([[  1,   2,   3, 212,   5,  14, 213, 214]]) tensor([215])
tensor([[  1,   2,   3,   4,   5, 206]]) tensor([207])
tensor([[ 42, 255,   2, 256,  83, 257, 258]]) tensor([259])
tensor([[42, 43, 44, 45, 46, 47, 48]]) tensor([49])
tensor([[  1,  87, 229, 230, 231, 232]]) tensor([233])
tensor([[ 42, 137,   2, 138,  39, 139]]) tensor([53])
tensor([[  1,   2,   3,  92, 137,  19,   3,  45]]) tensor([185])
tensor([[ 10,  29, 130, 131]]) tensor([132])
tensor([[ 42, 101,   2,   3,  17]]) tensor([102])

In [13]:
# Build Our RNN Model
import torch.nn as nn
class RNN(nn.Module):
  def __init__(self,vocab_size):
    super().__init__()

    self.embedding = nn.Embedding(vocab_size,embedding_dim=50)
    self.rnn = nn.RNN(50,64,batch_first=True)
    self.fc = nn.Linear(64,vocab_size)

  def forward(self,ques):
    embedded_ques = self.embedding(ques)
    hidden,final = self.rnn(embedded_ques)
    output = self.fc(final.squeeze(0))
    return output

In [14]:
x = nn.Embedding(324, embedding_dim=50)
y = nn.RNN(50, 64, batch_first=True)
z = nn.Linear(64, 324)

a = dataset[0][0].reshape(1,6)
print("shape of a:", a.shape)
b = x(a)
print("shape of b:", b.shape)
c, d = y(b)
print("shape of c:", c.shape)
print("shape of d:", d.shape)

e = z(d.squeeze(0))
print("shape of e:", e.shape)

shape of a: torch.Size([1, 6])
shape of b: torch.Size([1, 6, 50])
shape of c: torch.Size([1, 6, 64])
shape of d: torch.Size([1, 1, 64])
shape of e: torch.Size([1, 324])

In [15]:
model = RNN(len(vocab))
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr=0.001)

In [16]:
## Training Loop
epochs = 100
for epoch in range(epochs):
  total_loss = 0
  for ques,ans in dataloader:
    optimizer.zero_grad()

    # forward pass
    output = model(ques)

    # loss output shape (1,324) - (1)
    loss = criterion(output,ans[0])

    # gradients
    loss.backward()

    # update
    optimizer.step()
    total_loss+=loss.item()
  print(f"Epoch:{epoch+1} & Loss:{total_loss:.4f}")

Epoch:1 & Loss:522.1703
Epoch:2 & Loss:456.8388
Epoch:3 & Loss:380.8559
Epoch:4 & Loss:313.5557
Epoch:5 & Loss:259.9011
Epoch:6 & Loss:210.0063
Epoch:7 & Loss:166.1619
Epoch:8 & Loss:127.6564
Epoch:9 & Loss:97.1618
Epoch:10 & Loss:73.8930
Epoch:11 & Loss:56.8514
Epoch:12 & Loss:44.4807
Epoch:13 & Loss:35.2400
Epoch:14 & Loss:28.7478
Epoch:15 & Loss:23.6350
Epoch:16 & Loss:19.7260
Epoch:17 & Loss:16.5858
Epoch:18 & Loss:14.1460
Epoch:19 & Loss:12.0662
Epoch:20 & Loss:10.4303
Epoch:21 & Loss:9.0525
Epoch:22 & Loss:7.9920
Epoch:23 & Loss:7.0613
Epoch:24 & Loss:6.3294
Epoch:25 & Loss:5.6636
Epoch:26 & Loss:5.1191
Epoch:27 & Loss:4.6399
Epoch:28 & Loss:4.2299
Epoch:29 & Loss:3.8423
Epoch:30 & Loss:3.5269
Epoch:31 & Loss:3.2401
Epoch:32 & Loss:2.9884
Epoch:33 & Loss:2.7597
Epoch:34 & Loss:2.5551
Epoch:35 & Loss:2.3686
Epoch:36 & Loss:2.2038
Epoch:37 & Loss:2.0523
Epoch:38 & Loss:1.9130
Epoch:39 & Loss:1.7860
Epoch:40 & Loss:1.6708
Epoch:41 & Loss:1.5653
Epoch:42 & Loss:1.4684
Epoch:43 & Loss:1.3783
Epoch:44 & Loss:1.2930
Epoch:45 & Loss:1.2153
Epoch:46 & Loss:1.1432
Epoch:47 & Loss:1.0780
Epoch:48 & Loss:1.0168
Epoch:49 & Loss:0.9585
Epoch:50 & Loss:0.9039
Epoch:51 & Loss:0.8548
Epoch:52 & Loss:0.8076
Epoch:53 & Loss:0.7649
Epoch:54 & Loss:0.7223
Epoch:55 & Loss:0.6839
Epoch:56 & Loss:0.6474
Epoch:57 & Loss:0.6133
Epoch:58 & Loss:0.5819
Epoch:59 & Loss:0.5514
Epoch:60 & Loss:0.5232
Epoch:61 & Loss:0.4970
Epoch:62 & Loss:0.4715
Epoch:63 & Loss:0.4485
Epoch:64 & Loss:0.4257
Epoch:65 & Loss:0.4040
Epoch:66 & Loss:0.3841
Epoch:67 & Loss:0.3653
Epoch:68 & Loss:0.3475
Epoch:69 & Loss:0.3307
Epoch:70 & Loss:0.3148
Epoch:71 & Loss:0.2992
Epoch:72 & Loss:0.2849
Epoch:73 & Loss:0.2714
Epoch:74 & Loss:0.2588
Epoch:75 & Loss:0.2462
Epoch:76 & Loss:0.2347
Epoch:77 & Loss:0.2234
Epoch:78 & Loss:0.2129
Epoch:79 & Loss:0.2029
Epoch:80 & Loss:0.1933
Epoch:81 & Loss:0.1842
Epoch:82 & Loss:0.1758
Epoch:83 & Loss:0.1678
Epoch:84 & Loss:0.1597
Epoch:85 & Loss:0.1525
Epoch:86 & Loss:0.1453
Epoch:87 & Loss:0.1387
Epoch:88 & Loss:0.1323
Epoch:89 & Loss:0.1262
Epoch:90 & Loss:0.1204
Epoch:91 & Loss:0.1149
Epoch:92 & Loss:0.1098
Epoch:93 & Loss:0.1047
Epoch:94 & Loss:0.0999
Epoch:95 & Loss:0.0954
Epoch:96 & Loss:0.0911
Epoch:97 & Loss:0.0870
Epoch:98 & Loss:0.0830
Epoch:99 & Loss:0.0792
Epoch:100 & Loss:0.0757

In [17]:
def predict(model, question, threshold=0.5):

  # convert question to numbers
  numerical_question = text_indices(question, vocab)

  # tensor
  question_tensor = torch.tensor(numerical_question).unsqueeze(0)

  # send to model
  output = model(question_tensor)

  # convert logits to probs
  probs = torch.nn.functional.softmax(output, dim=1)

  # find index of max prob
  value, index = torch.max(probs, dim=1)

  if value < threshold:
    print("I don't know")
  print(list(vocab.keys())[index])

In [18]:
predict(model, "What is the largest planet in our solar system?")

jupiter

In [19]:
list(vocab.keys())[7]

'paris'

In [20]:
predict(model, "Who painted the Mona Lisa?")

leonardo-da-vinci