#### ***Pandas For Data Science***

In [2]:
import numpy as np 
import pandas as pd 

df = pd.DataFrame({
     "name":["Ankit","Alex","Muskan","Mehak"],
     "cgpa":[8,7,8.5,9]
})
df

     name  cgpa
0   Ankit   8.0
1    Alex   7.0
2  Muskan   8.5
3   Mehak   9.0

In [3]:
type(df)

pandas.core.frame.DataFrame

In [4]:
s = pd.Series([23,34,45,78,88])
print(s)
print(type(s))

0    23
1    34
2    45
3    78
4    88
dtype: int64
<class 'pandas.core.series.Series'>

In [5]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
## custom indexing
series = pd.Series([23,44,57,89],index=["A","B","C","D"])
series

A    23
B    44
C    57
D    89
dtype: int64

In [8]:
## Vectorized operation
s1 = pd.Series([1,2,3,4])
s2 = pd.Series([7,8,9,10])
print(s1+s2)

0     8
1    10
2    12
3    14
dtype: int64

In [9]:
## Mutable Values but immutable size
s = pd.Series([1,2,3,4,57,8,9])
s[2] = 120
print(s)

changed_series = s.drop(1)
print(changed_series)

0      1
1      2
2    120
3      4
4     57
5      8
6      9
dtype: int64
0      1
2    120
3      4
4     57
5      8
6      9
dtype: int64

In [10]:
## Datafram in pandas  using (Dictionary)
info = {
    "Name" : ["Adam", "Eve", "Bob"],
    "Marks" : [78, 99, 85],
    "Grade" : ['B', 'O', 'A']
}

df = pd.DataFrame(info)
df

   Name  Marks Grade
0  Adam     78     B
1   Eve     99     O
2   Bob     85     A

In [11]:
print(df.index)  # row labels
print(df.columns) # columns label

RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Marks', 'Grade'], dtype='object')

In [13]:
## Dataframe in pandas  using (Numpy Array)
arr = np.array([[1,2,3],[4,5,7],[8,9,10]])
df = pd.DataFrame(arr,columns=['A','B','C'])
df

   A  B   C
0  1  2   3
1  4  5   7
2  8  9  10

In [14]:
## Dataframe in pandas  using (Lists)
lst = [["Ankit",99],["Kush",97],["Kavi",90],["Ankit",95]]
df = pd.DataFrame(lst,columns=["Name","Marks"])
df

    Name  Marks
0  Ankit     99
1   Kush     97
2   Kavi     90
3  Ankit     95

In [17]:
# Performing Pandas Operations 
df = pd.read_csv("./data/amazoan.csv")
df.head()

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,0.00,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,0.05,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298
2,ORD0000003,2022-05-10,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,0.10,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908
3,ORD0000004,2023-07-18,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,0.15,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164
4,ORD0000005,2023-02-04,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,0.25,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411

In [18]:
df.tail()

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
99995,ORD0099996,2023-03-07,CUST001356,Karan Joshi,P00047,Memory Card 128GB,Electronics,Apex,2,492.34,0.00,78.77,2.75,1066.20,UPI,Delivered,Jacksonville,FL,India,SELL00041
99996,ORD0099997,2021-11-24,CUST031254,Sunita Kapoor,P00046,Car Charger,Sports & Outdoors,Apex,5,449.30,0.00,179.72,6.07,2432.29,Credit Card,Delivered,San Jose,CA,United States,SELL01449
99997,ORD0099998,2023-04-29,CUST012579,Aman Gupta,P00030,Dress Shirt,Sports & Outdoors,BrightLux,4,232.40,0.00,74.37,12.43,1016.40,Cash on Delivery,Delivered,Indianapolis,IN,United States,SELL00028
99998,ORD0099999,2021-11-01,CUST026243,Simran Gupta,P00046,Car Charger,Sports & Outdoors,HomeEase,1,294.05,0.00,23.52,13.09,330.66,Debit Card,Delivered,Charlotte,NC,United States,SELL00324
99999,ORD0100000,2021-12-04,CUST029492,Sunita Reddy,P00019,LED Desk Lamp,Home & Kitchen,CoreTech,5,166.70,0.05,63.35,3.34,858.52,Debit Card,Delivered,New York,NY,United States,SELL00761

In [19]:
df.sample(4)

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
34444,ORD0034445,2021-05-19,CUST025563,Aditya Mehta,P00038,External HDD 2TB,Clothing,Apex,2,538.98,0.05,81.92,12.28,1118.26,Credit Card,Delivered,San Jose,CA,United States,SELL00237
90263,ORD0090264,2021-02-27,CUST003131,Neha Joshi,P00046,Car Charger,Toys & Games,CoreTech,1,9.67,0.00,1.16,1.06,11.89,Debit Card,Delivered,Philadelphia,PA,India,SELL01908
10147,ORD0010148,2020-06-24,CUST008108,Sneha Patel,P00046,Car Charger,Toys & Games,FitLife,2,72.71,0.00,7.27,0.14,152.83,Credit Card,Delivered,San Jose,CA,India,SELL01929
93320,ORD0093321,2022-04-15,CUST012380,Sahil Verma,P00022,Water Bottle,Sports & Outdoors,ReadMore,1,546.52,0.20,52.47,0.83,490.52,Credit Card,Shipped,Dallas,TX,United States,SELL00534

In [20]:
df.shape

(100000, 20)

In [21]:
df.isnull().sum()

OrderID          0
OrderDate        0
CustomerID       0
CustomerName     0
ProductID        0
ProductName      0
Category         0
Brand            0
Quantity         0
UnitPrice        0
Discount         0
Tax              0
ShippingCost     0
TotalAmount      0
PaymentMethod    0
OrderStatus      0
City             0
State            0
Country          0
SellerID         0
dtype: int64

In [22]:
df.columns

Index(['OrderID', 'OrderDate', 'CustomerID', 'CustomerName', 'ProductID',
       'ProductName', 'Category', 'Brand', 'Quantity', 'UnitPrice', 'Discount',
       'Tax', 'ShippingCost', 'TotalAmount', 'PaymentMethod', 'OrderStatus',
       'City', 'State', 'Country', 'SellerID'],
      dtype='object')

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   OrderID        100000 non-null  object
 1   OrderDate      100000 non-null  object
 2   CustomerID     100000 non-null  object
 3   CustomerName   100000 non-null  object
 4   ProductID      100000 non-null  object
 5   ProductName    100000 non-null  object
 6   Category       100000 non-null  object
 7   Brand          100000 non-null  object
 8   Quantity       100000 non-null  int64
 9   UnitPrice      100000 non-null  float64
 10  Discount       100000 non-null  float64
 11  Tax            100000 non-null  float64
 12  ShippingCost   100000 non-null  float64
 13  TotalAmount    100000 non-null  float64
 14  PaymentMethod  100000 non-null  object
 15  OrderStatus    100000 non-null  object
 16  City           100000 non-null  object
 17  State          100000 non-null  object
 18  Country        100000 non-null  object
 19  SellerID       100000 non-null  object
dtypes: float64(5), int64(1), object(14)
memory usage: 15.3+ MB

In [24]:
df.describe()

,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,3.001400,302.905748,0.074226,68.468902,7.406660,918.256479
std,1.413548,171.840797,0.082583,74.131180,4.324057,724.508332
min,1.000000,5.000000,0.000000,0.000000,0.000000,4.270000
25%,2.000000,154.190000,0.000000,15.920000,3.680000,340.890000
50%,3.000000,303.070000,0.050000,45.250000,7.300000,714.315000
75%,4.000000,451.500000,0.100000,96.060000,11.150000,1349.765000
max,5.000000,599.990000,0.300000,538.460000,15.000000,3534.980000

In [29]:
df.head()

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,0.00,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,0.05,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298
2,ORD0000003,2022-05-10,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,0.10,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908
3,ORD0000004,2023-07-18,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,0.15,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164
4,ORD0000005,2023-02-04,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,0.25,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411

In [32]:
# Selecting Rows & Columns 
df.loc[3,"Country"]

'India'

In [33]:
df.iloc[2,3]

'Sneha Singh'

In [34]:
df.loc[3,["Country","City"]]

Country        India
City       Charlotte
Name: 3, dtype: object

In [35]:
df.loc[0:5,["Country","City","Tax"]] # end is inclusive

         Country         City     Tax
0          India   Washington    0.00
1  United States   Fort Worth   19.10
2  United States       Austin    7.57
3          India    Charlotte   11.42
4         Canada  San Antonio   38.67
5  United States  Los Angeles  215.87

In [36]:
df.iloc[0:5, 1:3]

    OrderDate  CustomerID
0  2023-01-31  CUST001504
1  2023-12-30  CUST000178
2  2022-05-10  CUST047516
3  2023-07-18  CUST030059
4  2023-02-04  CUST048677

In [40]:
## Filtering & Querying Data.
filter_df = df["UnitPrice"] > 342
df[filter_df].count()

OrderID          43503
OrderDate        43503
CustomerID       43503
CustomerName     43503
ProductID        43503
ProductName      43503
Category         43503
Brand            43503
Quantity         43503
UnitPrice        43503
Discount         43503
Tax              43503
ShippingCost     43503
TotalAmount      43503
PaymentMethod    43503
OrderStatus      43503
City             43503
State            43503
Country          43503
SellerID         43503
dtype: int64

In [41]:
df[df["UnitPrice"] > 100][["Brand","Country"]]

            Brand        Country
0       BrightLux          India
1      UrbanStyle  United States
4        KiddoFun         Canada
5        ReadMore  United States
6      UrbanStyle      Australia
...           ...            ...
99995        Apex          India
99996        Apex  United States
99997   BrightLux  United States
99998    HomeEase  United States
99999    CoreTech  United States

[84106 rows x 2 columns]

In [42]:
df = df[(df["UnitPrice"] > 100) & (df["Brand"] == "UrbanStyle")][["Brand", "Country"]]
df

            Brand         Country
1      UrbanStyle   United States
6      UrbanStyle       Australia
26     UrbanStyle   United States
51     UrbanStyle   United States
57     UrbanStyle          Canada
...           ...             ...
99918  UrbanStyle   United States
99921  UrbanStyle  United Kingdom
99966  UrbanStyle          Canada
99987  UrbanStyle   United States
99989  UrbanStyle   United States

[8301 rows x 2 columns]

In [43]:
## cleaning
df = pd.read_csv("./data/employee.csv")
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000